id: jbossdemocentral-brms-loan-realtime-decision-server
title: JBoss BRMS Loan Realtime Decision Server Demo
github_repo_url: https://github.com/jbossdemocentral/brms-loan-realtime-decision-server-demo
technologies:
  - JBoss EAP
  - JBoss BRMS
summary: This demo project will provide you with an example of creating, deploying and leveraging a set of rules (decision table) in a Realtime Decision Server. You will be given examples of calling the rules as if using it from an application with the RestAPI that is exposed. There are two options for you to install this project; local and containerized.
level: Beginner
product: brms
author: Edson Tirelli, Eric D. Schabell 
